Produce.create(produce: "Apple", image: "./image/apple.jpg" type: "fruit", price: 1.50, quantity: 15, expiring_soon: true, expiring_price: 0.89, expiring_quantity: 2, user_id: 1)
Produce.create(produce: "Banana", image: "./image/banana.jpg" type: "fruit",price: 0.96, quantity: 7, expiring_soon: true, expiring_price: 1.29, expiring_quantity: 2, user_id: 1)
Produce.create(produce: "Blueberry", image: "./image/blueberry.jpg" type: "fruit", price: 2.21, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Broccoli", image: "./image/broccoli.jpg" type: "vegetable", price: 2.91, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Cantalope", image: "./image/cantalope.jpg" type: "fruit", price: 3.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Cauliflower", image: "./image/cauliflower.jpg" type: "vegetable", price: 3.86, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Carrot", image: "./image/carrot.jpg" type: "vegetable", price: 2.82, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Cherry", image: "./image/cherry.jpg" type: "fruit", price: 0.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Citrus", image: "./image/citrus.jpg" type: "fruit", price: 0.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Cranberry", image: "./image/cranberry.jpg" type: "fruit", price: 0.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Cucumber", image: "./image/cucumber.jpg" type: "vegetable", price: 0.94, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Eggplant", image: "./image/eggplant.jpg" type: "vegetable", price: 2.62, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Garlic", image: "./image/garlic.jpg" type: "vegetable", price: 5.16, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Grape", image: "./image/grape.jpg" type: "fruit", price: 2.25, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Kiwi", image: "./image/kiwi.jpg" type: "fruit", price: 0.49, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Lemon", image: "./image/lemon.jpg" type: "fruit", price: 1.58, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Lettuce", image: "./image/lettuce.jpg" type: "vegetable", price: 3.91, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Lime", image: "./image/lime.jpg" type: "fruit", price: 2.31, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Mango", image: "./image/mango.jpg" type: "fruit", price: 0.91, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Mushroom", image: "./image/mushroom.jpg" type: "vegetable", price: 2.44, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Olives", image: "./image/olives.jpg" type: "vegetable", price: 0.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Onion", image: "./image/onion.jpg" type: "vegetable", price: 0.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Orange", image: "./image/orange.jpg" type: "fruit", price: 1.18, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Peach", image: "./image/peach.jpg" type: "fruit", price: 0.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Pineapple", image: "./image/pineapple.jpg" type: "fruit", price: 4.86, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Potato", image: "./image/potato.jpg" type: "vegetable", price: 1.29, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Plum", image: "./image/plum.jpg" type: "fruit", price: 0.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Raspberry", image: "./image/raspberry.jpg" type: "fruit", price: 5.54, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Scallion", image: "./image/scallion.jpg" type: "vegetable", price: 1.53, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Spinach", image: "./image/spinach.jpg" type: "vegetable", price: 6.95, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Strawberry", image: "./image/strawberry.jpg" type: "fruit", price: 0.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Sweet Potato", image: "./image/sweet potato.jpg" type: "vegetable", price: 1.75, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Tomato", image: "./image/tomato.jpg" type: "vegetable", price: 1.39, quantity: 20, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 10, user_id: 1)
Produce.create(produce: "Watermelon", image: "./image/watermelon.jpg" type: "fruit", price: 2.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)
Produce.create(produce: "Zucchini", image: "./image/zucchini.jpg" type: "vegetable", price: 1.99, quantity: 13, expiring_soon: true, expiring_price: 0.79, expiring_quantity: 3, user_id: 1)



puts 'done'